version: '3'

x-jellyfish-template: &jellyfish-template
  image: "ghcr.io/jellyfish-dev/jellyfish:${TAG:-edge}"
  environment: &jellyfish-environment
    ERLANG_COOKIE: ${SERVER_API_TOKEN}
    SERVER_API_TOKEN: ${SERVER_API_TOKEN}
    SECRET_KEY_BASE: ${SECRET_KEY_BASE}
    NODES: "app@jellyfish1 app@jellyfish2"
    USE_INTEGRATED_TURN: "true"
    INTEGRATED_TURN_IP: "${EXTERNAL_IP}"
    INTEGRATED_TURN_LISTEN_IP: "0.0.0.0"
    CHECK_ORIGIN: false
  restart: unless-stopped

services:

  jellyfish1:
    <<: *jellyfish-template
    container_name: jellyfish1
    environment:
      <<: *jellyfish-environment
      INTEGRATED_TURN_PORT_RANGE: "50000-50500"
      INTEGRATED_TCP_TURN_PORT: "49999"
      VIRTUAL_HOST: "${JELLYFISH_ADDRESS:-$EXTERNAL_IP}"
      PORT: 5002
      RELEASE_NODE: app@jellyfish1
      NODE_NAME: app@jellyfish1
    ports:
      - "5002:5002"
      - "49999:49999"
      - "50000-50500:50000-50500/udp"

  jellyfish2:
    <<: *jellyfish-template
    container_name: jellyfish2
    environment:
      <<: *jellyfish-environment
      INTEGRATED_TURN_PORT_RANGE: "50501-51000"
      INTEGRATED_TCP_TURN_PORT: "499998"
      VIRTUAL_HOST: "${JELLYFISH_ADDRESS:-$EXTERNAL_IP}"
      PORT: 5003
      RELEASE_NODE: app@jellyfish2
      NODE_NAME: app@jellyfish2
    ports:
      - "5003:5003"
      - "49998:49998"
      - "50501-51000:50501-51000/udp"

  frontend:
    build:
      context: ./assets
      dockerfile: ./Dockerfile
      args:
        IS_REVERSY_PROXY_USED: ${IS_REVERSY_PROXY_USED:-false}
        JELLYFISH_ADDRESS: ${JELLYFISH_ADDRESS:-$DOMAIN:5002}
        BACKEND_ADDRESS: ${BACKEND_ADDRESS:-$DOMAIN:5004}
    container_name: frontend
    restart: unless-stopped
    depends_on:
      - backend
      - jellyfish1
      - jellyfish2
    ports:
      - "5005:5005"

  backend:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: backend
    environment:
      SECRET_KEY_BASE: ${SECRET_KEY_BASE}
      JELLYFISH_ADDRESSES: ${JELLYFISH_ADDRESSES:-jellyfish1:5002 jellyfish2:5003}
      SECURE_CONNECTION_JELLYFISH: ${SECURE_CONNECTION:-false}
      JELLYFISH_API_TOKEN: ${SERVER_API_TOKEN}
      PHX_SERVER: "true"
      PHX_HOST: ${BACKEND_ADDRESS:-$DOMAIN}
      PORT: 5004
    restart: unless-stopped
    depends_on:
      - jellyfish1
      - jellyfish2
    ports:
      - "5004:5004"
