version: '3'

services:
  jellyfish:
    image: "ghcr.io/jellyfish-dev/jellyfish:${TAG:-edge}"
    # image: "jellyfish_test"
    restart: unless-stopped
    environment:
      BIND_LOCALHOST: "true"
      VIRTUAL_HOST: "${DOMAIN}"
      USE_INTEGRATED_TURN: "true"
      INTEGRATED_TURN_IP: "${INTEGRATED_TURN_IP}"
      INTEGRATED_TURN_LISTEN_IP: "0.0.0.0"
      INTEGRATED_TURN_PORT_RANGE: "50000-50500"
      INTEGRATED_TCP_TURN_PORT: "49999"
      SERVER_API_TOKEN: ${SERVER_API_TOKEN}
      PORT: 5002
      SECRET_KEY_BASE: ${SECRET_KEY_BASE}
    healthcheck:
      test: >
        curl --fail -H "authorization: Bearer development" http://jellyfish:5002/room || exit 1
      interval: 3s
      retries: 2
      timeout: 2s
      start_period: 30s
    ports:
      - "5002:5002"
      - "49999:49999"
      - "50000-50500:50000-50500/udp"
    networks:
      - jellyfish_network

  frontend:
    build:
      context: ./assets
      dockerfile: ./Dockerfile
      args:
        JELLYFISH_IP: ${MACHINE_IP:-localhost}
        JELLYFISH_PORT: 5002
        BACKEND_IP: ${MACHINE_IP:-localhost}
        BACKEND_PORT: 5004
    restart: unless-stopped
    ports:
      - "5005:5005"
    depends_on:
      - backend
      - jellyfish
    networks:
      - jellyfish_network

  backend:
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      SECRET_KEY_BASE: ${SECRET_KEY_BASE}
      JELLYFISH_IP: "jellyfish"
      JELLYFISH_PORT: 5002
      JELLYFISH_API_TOKEN: ${SERVER_API_TOKEN}
      PHX_SERVER: true
      PHX_HOST: "${DOMAIN}"
      PORT: 5004
    restart: unless-stopped
    ports:
      - "5004:5004"
    depends_on:
      - jellyfish
    networks:
      - jellyfish_network

networks:
  jellyfish_network:
    driver: bridge
