version: '2.2'

services:
  frontend:
    build:
      context: ./assets
      dockerfile: ./Dockerfile
      args:
        FE_BE_HOST: ${BE_HOST:-$DOMAIN:5004}
        FISHJAM_ROOM_VERSION: ${FISHJAM_ROOM_VERSION}
        JELLYFISH_VERSION: ${JELLYFISH_VERSION}
    container_name: frontend
    restart: unless-stopped
    depends_on:
      - backend
    ports:
      - "5005:5005"

  backend:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: backend
    environment:
      BE_PORT: 5004
      BE_HOST: ${BE_HOST:-$DOMAIN}
      BE_PHX_SERVER: "true"
      BE_JF_SECURE_CONNECTION: ${BE_JF_SECURE_CONNECTION:-false}
      BE_JF_SERVER_API_TOKEN: ${JF_SERVER_API_TOKEN}
      BE_JF_ADDRESSES: ${BE_JF_ADDRESSES:-$JF1_IP:$JF_PORT $JF2_IP:$JF_PORT}
    restart: unless-stopped
    ports:
      - "5004:5004"

