version: '3.8'

x-jellyfish-template: &jellyfish-template
  image: "ghcr.io/jellyfish-dev/jellyfish:${JELLYFISH_VERSION:-edge}"
  restart: unless-stopped
  environment: &jellyfish-environment
    JF_SERVER_API_TOKEN: ${JF_SERVER_API_TOKEN:-development}
    JF_CHECK_ORIGIN: "${JF_CHECK_ORIGIN:-false}"
    JF_DIST_ENABLED: "${JF_DIST_ENABLED:-true}"
    JF_DIST_NODES: "app@jellyfish1 app@jellyfish2"
    JF_WEBRTC_TURN_IP: $EXTERNAL_IP
    JF_WEBRTC_TURN_LISTEN_IP: "0.0.0.0"

services:
  jellyfish1:
    <<: *jellyfish-template
    container_name: jellyfish1
    environment:
      <<: *jellyfish-environment
      JF_HOST: "${JF1_HOST:-${JF1_IP:-$EXTERNAL_IP}:5002}"
      JF_PORT: 5002
      JF_DIST_NODE_NAME: app@jellyfish1
      JF_WEBRTC_TURN_PORT_RANGE: "50000-50100"
      JF_WEBRTC_TURN_TCP_PORT: "49999"
    ports:
      - "5002:5002"
      - "49999:49999"
      - "50000-50100:50000-50100/udp"

  jellyfish2:
    <<: *jellyfish-template
    restart: unless-stopped
    container_name: jellyfish2
    environment:
      <<: *jellyfish-environment
      JF_HOST: "${JF2_HOST:-${JF2_IP:-$EXTERNAL_IP}:5003}"
      JF_PORT: 5003
      JF_DIST_NODE_NAME: app@jellyfish2
      JF_WEBRTC_TURN_PORT_RANGE: "50101-50200"
      JF_WEBRTC_TURN_TCP_PORT: "49998"
    ports:
      - "5003:5003"
      - "49998:49998"
      - "50101-50200:50101-50200/udp"

  frontend:
    build:
      context: ./assets
      dockerfile: ./Dockerfile
      args:
        FE_BE_HOST: ${BE_HOST:-$DOMAIN:5004}
        JELLYFISH_VERSION: ${JELLYFISH_VERSION:-0.3.0}
        JELLYROOM_VERSION: ${JELLYROOM_VERSION:-build}
    container_name: frontend
    restart: unless-stopped
    depends_on:
      - backend
      - jellyfish1
      - jellyfish2
    ports:
      - "5005:5005"

  backend:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: backend
    environment:
      BE_PORT: 5004
      BE_HOST: ${BE_HOST:-$DOMAIN}
      BE_PHX_SERVER: "true"
      BE_JF_ADDRESSES: ${BE_JF_ADDRESSES:-jellyfish1:5002 jellyfish2:5003}
      BE_JF_SECURE_CONNECTION: ${BE_JF_SECURE_CONNECTION:-false}
      BE_JF_SERVER_API_TOKEN: ${JF_SERVER_API_TOKEN:-development}
    restart: unless-stopped
    depends_on:
      - jellyfish1
      - jellyfish2
    ports:
      - "5004:5004"
