version: '2.2'

services:
  frontend:
    build:
      context: ./assets
      dockerfile: ./Dockerfile
      args:
        ALLOY_HOST: ${ALLOY_HOST}
        FE_BE_HOST: ${BE_HOST:-$DOMAIN:5004}
        FISHJAM_ROOM_VERSION: ${FISHJAM_ROOM_VERSION}
        FISHJAM_VERSION: ${FISHJAM_VERSION}
    container_name: frontend
    restart: unless-stopped
    depends_on:
      - backend
    ports:
      - "5005:5005"

  backend:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: backend
    environment:
      BE_PORT: 5004
      BE_HOST: ${BE_HOST:-$DOMAIN}
      BE_PHX_SERVER: "true"
      BE_JF_SECURE_CONNECTION: ${BE_JF_SECURE_CONNECTION:-false}
      BE_JF_SERVER_API_TOKEN: ${JF_SERVER_API_TOKEN}
      BE_JF_ADDRESS: ${BE_JF_ADDRESS}
    restart: unless-stopped
    ports:
      - "5004:5004"

  grafana:
    build:
      context: ./infra/grafana/
      dockerfile: Dockerfile
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
    volumes:
      - grafana-storage:/var/lib/grafana

  loki:
    build:
      context: ./infra/loki/
      dockerfile: Dockerfile
    container_name: loki
    command: -config.file=/etc/loki/local-config.yaml
    volumes:
      - loki-data:/loki

  grafana-alloy:
    build:
      context: ./infra/alloy/
      dockerfile: Dockerfile
    container_name: alloy
    env_file:
      - './.env.example'
    entrypoint:
      - '/bin/alloy'
      - 'run'
      - '--server.http.listen-addr=0.0.0.0:12345'
      - '--config.extra-args="-config.expand-env"'
      - '${ALLOY_CONFIG_PATH}/${ALLOY_CONFIG_FILE}'
    ports:
      - '12345:12345'
      - '8027:8027'

volumes:
  grafana-storage:
  loki-data:
