version: '2.2'

x-jellyfish-template: &jellyfish-template
  image: "ghcr.io/jellyfish-dev/jellyfish:${JELLYFISH_VERSION}"
  restart: unless-stopped
  environment: &jellyfish-environment
    JF_PORT: $JF_PORT
    JF_CHECK_ORIGIN: "${JF_CHECK_ORIGIN:-true}"
    JF_SERVER_API_TOKEN: ${JF_SERVER_API_TOKEN}
    JF_DIST_ENABLED: "${JF_DIST_ENABLED:-true}"
    JF_DIST_NODES: "app@$JF1_IP app@$JF2_IP"
    JF_WEBRTC_TURN_LISTEN_IP: "0.0.0.0"
    JF_WEBRTC_TURN_PORT_RANGE: "50000-50500"
    JF_WEBRTC_TURN_TCP_PORT: "49999"
  ports:
    - "5002:5002"
    - "49999:49999"
    - "4369:4369" # EPMD
    - "9000:9000"
    - "9568:9568"
    - "50000-50500:50000-50500/udp"

x-node-exporter: &node-exporter-template
  image: prom/node-exporter:v1.6.1
  restart: on-failure
  network_mode: host
  command:
    - --path.rootfs=/host
  volumes:
    - /:/host:ro,rslave

services:
  jellyfish1:
    <<: *jellyfish-template
    container_name: jellyfish1
    environment:
      <<: *jellyfish-environment
      JF_HOST: "${JF1_HOST:-$JF1_IP:$JF_PORT}"
      JF_DIST_NODE_NAME: app@$JF1_IP
      JF_WEBRTC_TURN_IP: "${JF1_IP}"

  jellyfish2:
    <<: *jellyfish-template
    container_name: jellyfish2
    environment:
      <<: *jellyfish-environment
      JF_HOST: "${JF2_HOST:-$JF2_IP:$JF_PORT}"
      JF_DIST_NODE_NAME: app@$JF2_IP
      JF_WEBRTC_TURN_IP: "${JF2_IP}"

  frontend:
    build:
      context: ./assets
      dockerfile: ./Dockerfile
      args:
        FE_BE_HOST: ${BE_HOST:-$DOMAIN:5004}
        JELLYROOM_VERSION: ${JELLYROOM_VERSION}
        JELLYFISH_VERSION: ${JELLYFISH_VERSION}
    container_name: frontend
    restart: unless-stopped
    depends_on:
      - backend
      - jellyfish1
    ports:
      - "5005:5005"

  backend:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: backend
    environment:
      BE_PORT: 5004
      BE_HOST: ${BE_HOST:-$DOMAIN}
      BE_PHX_SERVER: "true"
      BE_JF_SECURE_CONNECTION: ${BE_JF_SECURE_CONNECTION:-false}
      BE_JF_SERVER_API_TOKEN: ${JF_SERVER_API_TOKEN}
      BE_JF_ADDRESSES: ${BE_JF_ADDRESSES:-$JF1_IP:$JF_PORT $JF2_IP:$JF_PORT}
    restart: unless-stopped
    depends_on:
      - jellyfish1
    ports:
      - "5004:5004"

  prometheus:
    build:
      context: ./prometheus
      dockerfile: Dockerfile
      args:
        PROM_JELLYFISH_TARGETS: ${PROM_JELLYFISH_TARGETS:-jellyfish1:9568,jellyfish2:9568}
        PROM_NODE_TARGETS: ${PROM_NODE_TARGETS:-node_exporter:9100}
    container_name: prometheus
    restart: on-failure
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      - --storage.tsdb.path=/prometheus
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    volumes:
      - prometheus_data:/prometheus
    depends_on:
      - jellyfish1

  grafana:
    build:
      context: ./grafana
      dockerfile: Dockerfile
    container_name: grafana
    restart: on-failure
    volumes:
      - grafana_data:/var/lib/grafana
    depends_on:
      - prometheus
    environment:
      GF_SECURITY_ADMIN_PASSWORD: "${GF_SECURITY_ADMIN_PASSWORD}"
      GF_SECURITY_ADMIN_USER: "${GF_SECURITY_ADMIN_USER}"
    ports:
      - '3000:3000'
    expose:
      - 3000

  node-exporter1:
    <<: *node-exporter-template
    container_name: node_exporter1

  node-exporter2:
    <<: *node-exporter-template
    container_name: node_exporter2

  loki:
    image: grafana/loki:2.9.0
    build:
      context: ./loki
      dockerfile: Dockerfile
    volumes:
      - loki_data:/loki
    ports:
      - "3100:3100"

  promtail:
    build:
      context: ./promtail
      dockerfile: Dockerfile
      args:
        LOKI_ADDRESS: $LOKI_ADDRESS
    volumes:
      # to read container labels and logs
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/containers:/var/lib/docker/containers

volumes:
  grafana_data: {}
  prometheus_data: {}
  loki_data: {}
