version: '2.2'

x-jellyfish-template: &jellyfish-template
  image: "ghcr.io/jellyfish-dev/jellyfish:${TAG:-edge}"
  restart: unless-stopped
  environment: &jellyfish-environment
    USE_INTEGRATED_TURN: "true"
    INTEGRATED_TURN_LISTEN_IP: "0.0.0.0"
    INTEGRATED_TURN_PORT_RANGE: "50000-50500"
    INTEGRATED_TCP_TURN_PORT: "49999"
    SERVER_API_TOKEN: ${SERVER_API_TOKEN}
    SECRET_KEY_BASE: ${SECRET_KEY_BASE}
    RELEASE_DISTRIBUTION: name
    RELEASE_COOKIE: ${SERVER_API_TOKEN}
    PORT: 5002
    NODES: "app@jellyfish1 app@jellyfish2"
    CHECK_ORIGIN: "${CHECK_ORIGIN:-true}"
    BEAM_PORT: 9000
    ELIXIR_ERL_OPTIONS: "-kernel inet_dist_listen_min $BEAM_PORT inet_dist_listen_max $BEAM_PORT"
  ports:
    - "5002:5002"
    - "49999:49999"
    - "4369:4369" # EPMD
    - "9000:9000"
    - "50000-50500:50000-50500/udp"

services:
  jellyfish1:
    <<: *jellyfish-template
    container_name: jellyfish1
    environment:
      <<: *jellyfish-environment
      INTEGRATED_TURN_IP: "${JELLYFISH1_IP}"
      VIRTUAL_HOST: "${JELLYFISH1_ADDRESS:-$JELLYFISH1_IP}"
      JELLYFISH_ADDRESS: ${JELLYFISH1_ADDRESS}
      RELEASE_NODE: app@$JELLYFISH1_IP
      NODE_NAME: app@$JELLYFISH1_IP
      NODES: "app@$JELLYFISH1_IP app@$JELLYFISH2_IP"

  jellyfish2:
    <<: *jellyfish-template
    container_name: jellyfish2
    environment:
      <<: *jellyfish-environment
      INTEGRATED_TURN_IP: "${JELLYFISH2_IP}"
      VIRTUAL_HOST: "${JELLYFISH2_ADDRESS:-$JELLYFISH2_IP}"
      RELEASE_NODE: app@$JELLYFISH2_IP
      NODE_NAME: app@$JELLYFISH2_IP
      NODES: "app@$JELLYFISH1_IP app@$JELLYFISH2_IP"

  frontend:
    build:
      context: ./assets
      dockerfile: ./Dockerfile
      args:
        IS_REVERSY_PROXY_USED: ${IS_REVERSY_PROXY_USED:-false}
        BACKEND_ADDRESS: ${BACKEND_ADDRESS:-$DOMAIN:5004}
    container_name: frontend
    restart: unless-stopped
    depends_on:
      - backend
      - jellyfish1
    ports:
      - "5005:5005"

  backend:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: backend
    environment:
      SECRET_KEY_BASE: ${SECRET_KEY_BASE}
      JELLYFISH_ADDRESSES: ${JELLYFISH_ADDRESSES:-$JELLYFISH1_IP:5002 $JELLYFISH2_IP:5002}
      SECURE_CONNECTION_JELLYFISH: ${SECURE_CONNECTION:-false}
      JELLYFISH_API_TOKEN: ${SERVER_API_TOKEN}
      PHX_SERVER: "true"
      PHX_HOST: ${BACKEND_ADDRESS:-$DOMAIN}
      PORT: 5004
    restart: unless-stopped
    depends_on:
      - jellyfish1
    ports:
      - "5004:5004"

  prometheus:
    build:
      context: ./prometheus
      dockerfile: Dockerfile
    environment:
      TARGETS: ${PROMETHEUS_TARGETS:-jellyfish1:9568,jellyfish2:9568}
    container_name: prometheus
    restart: on-failure
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      - --storage.tsdb.path=/prometheus
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    volumes:
      - prometheus_data:/prometheus
    depends_on:
      - jellyfish1

  grafana:
    build:
      context: ./grafana
      dockerfile: Dockerfile
    container_name: grafana
    restart: on-failure
    volumes:
      - grafana_data:/var/lib/grafana
    depends_on:
      - prometheus
    environment:
      GF_SECURITY_ADMIN_PASSWORD: "${GF_SECURITY_ADMIN_PASSWORD}"
      GF_SECURITY_ADMIN_USER: "${GF_SECURITY_ADMIN_USER}"
    ports:
      - '3000:3000'
    expose:
      - 3000

volumes:
  grafana_data: {}
  prometheus_data: {}
