version: '3.7'

x-jellyfish-template: &jellyfish-template
  image: "ghcr.io/jellyfish-dev/jellyfish:${TAG:-edge}"
  restart: unless-stopped
  environment: &jellyfish-environment
    USE_INTEGRATED_TURN: "true"
    INTEGRATED_TURN_IP: $EXTERNAL_IP
    INTEGRATED_TURN_LISTEN_IP: "0.0.0.0"
    SERVER_API_TOKEN: ${SERVER_API_TOKEN}
    SECRET_KEY_BASE: ${SECRET_KEY_BASE}
    RELEASE_COOKIE: ${SERVER_API_TOKEN}
    NODES: "app@jellyfish1 app@jellyfish2"
    CHECK_ORIGIN: "${CHECK_ORIGIN:-false}"
    BEAM_PORT: 9000
    ELIXIR_ERL_OPTIONS: "-kernel inet_dist_listen_min $BEAM_PORT inet_dist_listen_max $BEAM_PORT"

services:
  jellyfish1:
    <<: *jellyfish-template
    container_name: jellyfish1
    environment:
      <<: *jellyfish-environment
      INTEGRATED_TURN_PORT_RANGE: "50000-50500"
      INTEGRATED_TCP_TURN_PORT: "49999"
      VIRTUAL_HOST: "${JELLYFISH1_ADDRESS:-${JELLYFISH1_IP:-$EXTERNAL_IP}}"
      RELEASE_NODE: app@jellyfish1
      NODE_NAME: app@jellyfish1
      PORT: 5002
    ports:
      - "5002:5002"
      - "49999:49999"
      - "50000-50500:50000-50500/udp"

  jellyfish2:
    <<: *jellyfish-template
    restart: unless-stopped
    container_name: jellyfish2
    environment:
      <<: *jellyfish-environment
      INTEGRATED_TURN_PORT_RANGE: "50501-51000"
      INTEGRATED_TCP_TURN_PORT: "49998"
      VIRTUAL_HOST: "${JELLYFISH2_ADDRESS:-${JELLYFISH2_IP:-$EXTERNAL_IP}}"
      RELEASE_NODE: app@jellyfish2
      NODE_NAME: app@jellyfish2
      PORT: 5003
    ports:
      - "5003:5003"
      - "49998:49998"
      - "50501-51000:50501-51000/udp"

  frontend:
    build:
      context: ./assets
      dockerfile: ./Dockerfile
      args:
        BACKEND_ADDRESS: ${BACKEND_ADDRESS:-$DOMAIN:5004}
    container_name: frontend
    restart: unless-stopped
    depends_on:
      - backend
      - jellyfish1
      - jellyfish2
    ports:
      - "5005:5005"

  backend:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: backend
    environment:
      SECRET_KEY_BASE: ${SECRET_KEY_BASE}
      JELLYFISH_ADDRESSES: ${JELLYFISH_ADDRESSES:-jellyfish1:5002 jellyfish2:5003}
      SECURE_CONNECTION_JELLYFISH: ${SECURE_CONNECTION:-false}
      JELLYFISH_API_TOKEN: ${SERVER_API_TOKEN}
      PHX_SERVER: "true"
      PHX_HOST: ${BACKEND_ADDRESS:-$DOMAIN}
      PORT: 5004
    restart: unless-stopped
    depends_on:
      - jellyfish1
      - jellyfish2
    ports:
      - "5004:5004"

  prometheus:
    build:
      context: ./prometheus
      dockerfile: Dockerfile
      args:
        TARGETS: ${PROMETHEUS_TARGETS:-jellyfish1:9568,jellyfish2:9568}
    container_name: prometheus
    restart: on-failure
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      - --storage.tsdb.path=/prometheus
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    volumes:
      - prometheus_data:/prometheus
    depends_on:
      - jellyfish1
      - jellyfish2

  grafana:
    build:
      context: ./grafana
      dockerfile: Dockerfile
    container_name: grafana
    restart: on-failure
    volumes:
      - grafana_data:/var/lib/grafana
    depends_on:
      - prometheus
    environment:
      GF_SECURITY_ADMIN_PASSWORD: "${GF_SECURITY_ADMIN_PASSWORD}"
      GF_SECURITY_ADMIN_USER: "${GF_SECURITY_ADMIN_USER}"
    ports:
      - '3000:3000'
    expose:
      - 3000

volumes:
  grafana_data: {}
  prometheus_data: {}
