version: '3.7'

x-jellyfish-template: &jellyfish-template
  image: "ghcr.io/jellyfish-dev/jellyfish:${TAG:-0.1.0-5ef4452}"
  restart: unless-stopped
  environment: &jellyfish-environment
    JF_SERVER_API_TOKEN: ${JF_SERVER_API_TOKEN}
    JF_CHECK_ORIGIN: "${JF_CHECK_ORIGIN:-false}"
    JF_DIST_ENABLED: "${JF_DIST_ENABLED:-true}"
    JF_DIST_NODES: "app@jellyfish1 app@jellyfish2"
    JF_WEBRTC_TURN_IP: $EXTERNAL_IP
    JF_WEBRTC_TURN_LISTEN_IP: "0.0.0.0"

services:
  jellyfish1:
    <<: *jellyfish-template
    container_name: jellyfish1
    environment:
      <<: *jellyfish-environment
      JF_PORT: 5002
      JF_HOST: "${JF1_HOST:-${JF1_IP:-$EXTERNAL_IP}:5002}"
      JF_DIST_MODE: sname
      JF_DIST_NODE_NAME: app@jellyfish1
      JF_WEBRTC_TURN_PORT_RANGE: "50000-50500"
      JF_WEBRTC_TURN_TCP_PORT: "49999"
    ports:
      - "5002:5002"
      - "49999:49999"
      - "50000-50500:50000-50500/udp"

  jellyfish2:
    <<: *jellyfish-template
    restart: unless-stopped
    container_name: jellyfish2
    environment:
      <<: *jellyfish-environment
      JF_PORT: 5003
      JF_HOST: "${JF2_HOST:-${JF2_IP:-$EXTERNAL_IP}:5003}"
      JF_DIST_MODE: sname
      JF_DIST_NODE_NAME: app@jellyfish2
      JF_WEBRTC_TURN_PORT_RANGE: "50501-51000"
      JF_WEBRTC_TURN_TCP_PORT: "49998"
    ports:
      - "5003:5003"
      - "49998:49998"
      - "50501-51000:50501-51000/udp"

  frontend:
    build:
      context: ./assets
      dockerfile: ./Dockerfile
      args:
        BE_HOST: ${BE_HOST:-$DOMAIN:5004}
    container_name: frontend
    restart: unless-stopped
    depends_on:
      - backend
      - jellyfish1
      - jellyfish2
    ports:
      - "5005:5005"

  backend:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: backend
    environment:
      BE_PORT: 5004
      BE_HOST: ${BE_HOST:-$DOMAIN}
      BE_PHX_SERVER: "true"
      BE_JF_ADDRESSES: ${BE_JF_ADDRESSES:-jellyfish1:5002 jellyfish2:5003}
      BE_JF_SECURE_CONNECTION: ${BE_JF_SECURE_CONNECTION:-false}
      BE_JF_SERVER_API_TOKEN: ${JF_SERVER_API_TOKEN}
    restart: unless-stopped
    depends_on:
      - jellyfish1
      - jellyfish2
    ports:
      - "5004:5004"

  prometheus:
    build:
      context: ./prometheus
      dockerfile: Dockerfile
      args:
        TARGETS: ${PROMETHEUS_TARGETS:-jellyfish1:9568,jellyfish2:9568}
    container_name: prometheus
    restart: on-failure
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      - --storage.tsdb.path=/prometheus
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    volumes:
      - prometheus_data:/prometheus
    depends_on:
      - jellyfish1
      - jellyfish2

  grafana:
    build:
      context: ./grafana
      dockerfile: Dockerfile
    container_name: grafana
    restart: on-failure
    volumes:
      - grafana_data:/var/lib/grafana
    depends_on:
      - prometheus
    environment:
      GF_SECURITY_ADMIN_PASSWORD: "${GF_SECURITY_ADMIN_PASSWORD}"
      GF_SECURITY_ADMIN_USER: "${GF_SECURITY_ADMIN_USER}"
    ports:
      - '3000:3000'
    expose:
      - 3000

volumes:
  grafana_data: {}
  prometheus_data: {}
