version: '3'

services:
  reverseproxy:
    build:
      context: ./reverse-proxy
      dockerfile: ./Dockerfile
    ports:
      - 80:80
      - 443:443
    restart: unless-stopped
    volumes:
      - ./certbot/conf:/etc/letsencrypt
    env_file:
      - .env
    networks:
      - jellyfish_network
    depends_on:
      - frontend
      - backend
      - jellyfish

  frontend:
    extends:
      file: docker-compose.yaml
      service: frontend
    build:
      args:
        IS_REVERSY_PROXY_USED: "true"
        JELLYFISH_ADDRESS: "${DOMAIN}:5002"
        BACKEND_ADDRESS: "${DOMAIN}:5004"
    networks:
      - jellyfish_network

  backend:
    extends:
      file: docker-compose.yaml
      service: backend
    environment:
      JELLYFISH_ADDRESS: jellyfish:5002
      SECURE_CONNECTION_JELLYFISH: false
      PHX_HOST: ${DOMAIN}
    networks:
      - jellyfish_network

  jellyfish:
    extends:
      file: docker-compose.yaml
      service: jellyfish
    environment:
      VIRTUAL_HOST: "${DOMAIN}"
      JELLYFISH_ADDRESS: jellyfish:5002
      SECURE_CONNECTION_JELLYFISH: false
      PHX_HOST: ${DOMAIN}
    networks:
      - jellyfish_network

networks:
  jellyfish_network:
    driver: bridge
