version: '3'

services:
  jellyfish:
    image: "ghcr.io/jellyfish-dev/jellyfish:${TAG:-edge}"
    container_name: jellyfish
    restart: unless-stopped
    environment:
      VIRTUAL_HOST: "${JELLYFISH_ADDRESS:-$DOMAIN}"
      USE_INTEGRATED_TURN: "true"
      INTEGRATED_TURN_IP: "${EXTERNAL_IP}"
      INTEGRATED_TURN_LISTEN_IP: "0.0.0.0"
      INTEGRATED_TURN_PORT_RANGE: "50000-50500"
      INTEGRATED_TCP_TURN_PORT: "49999"
      SERVER_API_TOKEN: ${SERVER_API_TOKEN}
      CHECK_ORIGIN: "${CHECK_ORIGIN:-true}"
      PORT: 5002
      SECRET_KEY_BASE: ${SECRET_KEY_BASE}
    ports:
      - "5002:5002"
      - "49999:49999"
      - "50000-50500:50000-50500/udp"

  frontend:
    build:
      context: ./assets
      dockerfile: ./Dockerfile
      args:
        JELLYFISH_ADDRESS: ${JELLYFISH_ADDRESS:-$DOMAIN:5002}
        BACKEND_ADDRESS: ${BACKEND_ADDRESS:-$DOMAIN:5004}
    container_name: frontend
    restart: unless-stopped
    depends_on:
      - backend
      - jellyfish
    ports:
      - "5005:5005"

  backend:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: backend
    environment:
      SECRET_KEY_BASE: ${SECRET_KEY_BASE}
      JELLYFISH_ADDRESS: ${JELLYFISH_ADDRESS:-jellyfish:5002}
      SECURE_CONNECTION_JELLYFISH: ${SECURE_CONNECTION:-false}
      JELLYFISH_API_TOKEN: ${SERVER_API_TOKEN}
      PHX_SERVER: "true"
      PHX_HOST: ${BACKEND_ADDRESS:-$DOMAIN}
      PORT: 5004
    restart: unless-stopped
    depends_on:
      - jellyfish
    ports:
      - "5004:5004"

  prometheus:
    build:
      context: ./prometheus
      dockerfile: Dockerfile
    container_name: prometheus
    restart: on-failure
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      - --storage.tsdb.path=/prometheus
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    volumes:
      - prometheus_data:/prometheus
    depends_on:
      - jellyfish

  grafana:
    build:
      context: ./grafana
      dockerfile: Dockerfile
    container_name: grafana
    restart: on-failure
    volumes:
      - grafana_data:/var/lib/grafana
    depends_on:
      - prometheus
    environment:
      GF_SECURITY_ADMIN_PASSWORD: "${GF_SECURITY_ADMIN_PASSWORD}"
      GF_SECURITY_ADMIN_USER: "${GF_SECURITY_ADMIN_USER}"
    ports:
      - '3000:3000'
    expose:
      - 3000

volumes:
  grafana_data: {}
  prometheus_data: {}
