version: 2.1
orbs:
  elixir: membraneframework/elixir@1

workflows:
  version: 2
  build:
    jobs:
      - elixir/build_test:
          cache-version: 2
      - elixir/test:
          cache-version: 2
      - elixir/lint:
          cache-version: 2
          docs: false

