version: 2.1
orbs:
  elixir: membraneframework/elixir@1

jobs:
  test:
    docker:
      - image: membraneframeworklabs/docker_membrane:latest
        environment:
          MIX_ENV: test
          SERVER_API_TOKEN: development
          SECRET_KEY_BASE: secret

      - image: ghcr.io/jellyfish-dev/jellyfish:latest      

    steps:
      - checkout
      - run: mix deps.get
      - run: mix test --warnings-as-errors

workflows:
  version: 2
  build:
    jobs:
      - elixir/build_test:
          cache-version: 2
      - test
      - elixir/lint:
          cache-version: 2
          docs: false

