version: 2.1
orbs:
  elixir: membraneframework/elixir@1

executors:
 machine_executor_amd64:
   machine:
     image: ubuntu-2204:2022.04.2
   environment:
     architecture: "amd64"
     platform: "linux/amd64"

jobs:
  test:
    executor: machine_executor_amd64
    steps:
      - checkout
      - run: docker compose -f docker-compose-integration.yaml run test

workflows:
  version: 2
  build:
    jobs:
      - elixir/build_test:
          cache-version: 2
      - test
      - elixir/lint:
          cache-version: 2
          docs: false
