global:
  scrape_interval: 2s

  external_labels:
    monitor: 'codelab-monitor'

scrape_configs:
  - job_name: 'fishjams'
    static_configs:
      - targets: [$PROM_FISHJAM_TARGETS]

  - job_name: 'nodes'
    static_configs:
      - targets: [$PROM_NODE_TARGETS]
