global:
  scrape_interval: 2s

  external_labels:
    monitor: 'codelab-monitor'

scrape_configs:
  - job_name: 'jellyfish1'
    static_configs:
      - targets: ['jellyfish1:9568']
  - job_name: 'jellyfish2'
    static_configs:
      - targets: ['${JELLYFISH2_IP:-jellyfish2}:9568']
