global:
  scrape_interval: 2s

  external_labels:
    monitor: 'codelab-monitor'

scrape_configs:
  - job_name: 'jellyfishes'
    static_configs:
      - targets: [$JELLYFISH_TARGETS]
  
  - job_name: 'nodes'
    static_configs:
      - targets: [$NODE_TARGETS]
