apiVersion: 1

deleteDatasources:
  - name: Prometheus
    orgId: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    orgId: 1
    uid: "PBFA97CFB590B2093"
    url: http://prometheus:9090
    editable: true
    basicAuth: false
    isDefault: true

  - name: Loki
    type: loki
    url: http://loki:3100
    isDefault: false