{
 "title": "Jellyfishes dashboard",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   { "name": "ds", "query": "prometheus" },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(jellyfish_rooms,instance)"
    }
   },
   {
    "name": "node",
    "label": "Node",
    "query": {
     "query": "label_values(node_uname_info,instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Rooms",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Current number of rooms",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 10, "x": 0, "y": 1 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(jellyfish_rooms{instance=~\"$instance\"}) by(instance)",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Rooms number",
     "type": "timeseries",
     "description": "Present the current number of rooms by jellyfish instance.",
     "gridPos": { "h": 8, "w": 14, "x": 10, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(jellyfish_rooms{instance=~\"$instance\"}) by(instance)",
       "legendFormat": "{{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Ingress & Egress",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Ingress throughput ($instance)",
     "type": "timeseries",
     "description": "Ingress throughput from each of the jellyfish instances",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "jellyfish_traffic_ingress_throughput_bytes_per_second{instance=~\"$instance\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Egress throughput ($instance)",
     "type": "timeseries",
     "description": "Egress throughput from each of the jellyfish instances",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "jellyfish_traffic_egress_throughput_bytes_per_second{instance=~\"$instance\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Ingress and Egress throughput ($instance)",
     "type": "timeseries",
     "description": "Ingress and Egress throughput from each of the jellyfish instances",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "jellyfish_traffic_ingress_throughput_bytes_per_second{instance=~\"$instance\"}",
       "legendFormat": "{{instance}} ingress"
      },
      {
       "expr": "jellyfish_traffic_egress_throughput_bytes_per_second{instance=~\"$instance\"}",
       "legendFormat": "{{instance}} egress"
      }
     ]
    }
   ]
  },
  {
   "title": "Resources",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "VM memory ($instance)",
     "type": "timeseries",
     "description": "VM usage from each of the jellyfish instances",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "vm_memory_total_bytes{instance=~\"$instance\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "VM total run queue lengths total ($instance)",
     "type": "timeseries",
     "description": "VM queue lengths from each of the jellyfish instances",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "vm_total_run_queue_lengths_total{instance=~\"$instance\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "VM total run queue lengths cpu  ($instance)",
     "type": "timeseries",
     "description": "VM queue lengths from each of the jellyfish instances",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "vm_total_run_queue_lengths_cpu{instance=~\"$instance\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "VM total run queue lengths io  ($instance)",
     "type": "timeseries",
     "description": "VM queue lengths from each of the jellyfish instances",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 35 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "vm_total_run_queue_lengths_io{instance=~\"$instance\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    }
   ]
  },
  { "title": "Node stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 } },
  {
   "title": "CPU percentage usage by node ($node)",
   "type": "timeseries",
   "description": "CPU usage from each of the nodes",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - (avg by (instance) (irate(node_cpu_seconds_total{mode=\"idle\", instance=~\"$node\"}[$__rate_interval])) * 100)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Average bytes received by node ($node)",
   "type": "timeseries",
   "description": "Average bytes received from each of the nodes",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "(avg by (instance) (irate(node_network_receive_bytes_total{instance=~\"$node\"}[$__rate_interval])))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Average bytes transmitted by node ($node)",
   "type": "timeseries",
   "description": "Average bytes transmitted from each of the nodes.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "(avg by (instance) (irate(node_network_transmit_bytes_total{instance=~\"$node\"}[$__rate_interval])))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Percentage of memory used by node ($node)",
   "type": "timeseries",
   "description": "The percentage of memory used by each node.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 * (1 - ((avg_over_time(node_memory_MemFree_bytes{instance=~\"$node\"}[$__rate_interval]) + avg_over_time(node_memory_Cached_bytes{instance=~\"$node\"}[$__rate_interval]) + avg_over_time(node_memory_Buffers_bytes{instance=~\"$node\"}[$__rate_interval])) / avg_over_time(node_memory_MemTotal_bytes{instance=~\"$node\"}[$__rate_interval])))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Number of allocated file descriptors by node ($node)",
   "type": "timeseries",
   "description": "Number of allocated file descriptors from each of the nodes.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(node_filefd_allocated{instance=~\"$node\"}) by(instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}