{
 "title": "Faro dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Metrics panel",
   "type": "table",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "avg(avg_over_time({kind=\"measurement\"} | logfmt | value_lcp != `` | unwrap value_lcp [$__auto]))"
    }
   ]
  },
  {
   "title": "Client logs",
   "type": "logs",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 11 },
   "targets": [
    {
     "expr": "{kind=\"log\"}"
    }
   ]
  },
  {
   "title": "Client events",
   "type": "logs",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 22 },
   "targets": [
    {
     "expr": "{kind=\"event\"}"
    }
   ]
  }
 ]
}