server:
  disable: true
  health_check_target: false

clients:
  - url: http://$LOKI_ADDRESS:3100/loki/api/v1/push
    external_labels:
      project: fishjam_room

scrape_configs:
  - job_name: docker
    # use docker.sock to filter containers
    docker_sd_configs:
      - host: "unix:///var/run/docker.sock"
        refresh_interval: 15s
    # use container name to create a loki label
    relabel_configs:
      - source_labels: ['__meta_docker_container_name']
        regex: '/(.*)'
        target_label: 'container'
