name: Staging Build and Deploy
on:
  push:
    branches:
      - "debug-staging"
    paths:
      - "**"

env:
  DOMAIN: room.fishjam.work
  BE_HOST: server.room.fishjam.work
  PROJECT: staging
  COMPOSE_FILE_NAME: docker-compose-deploy.yaml

jobs:
  deploy1:
    runs-on: ubuntu-latest
    steps:
      - name: Debug staging
        uses: JimCronqvist/action-ssh@master
        with:
          hosts: ${{ secrets.STAGING_HOST_2 }}
          privateKey: ${{ secrets.SSH_PRIV_KEY }}
          command: |
            ls -al

