name: Staging Build and Deploy
on:
  push:
    branches: 
      - "main"

env: 
  DOMAIN: jellyroom.membrane.work
  JF1_HOST: jellyfish.membrane.work
  JF2_HOST: jellyfish1.membrane.work
  BE_HOST: server.jellyroom.membrane.work
  PROJECT: staging
  COMPOSE_FILE_NAME: docker-compose-deploy.yaml

jobs:
  deploy1:
    runs-on: ubuntu-latest
    steps:  
      - uses: actions/checkout@v2

      - name: Prepare .env file for the deployment
        id: variables_population
        run: |
          echo "DOMAIN=${{env.DOMAIN}} 
          JF_SERVER_API_TOKEN=${{secrets.SERVER_API_TOKEN}}
          JF_CHECK_ORIGIN=false
          JF_PORT=5002
          JF1_IP=${{secrets.STAGING_IP}}
          JF2_IP=${{secrets.STAGING2_IP}}
          JF1_HOST=${{env.JF1_HOST}}
          JF2_HOST=${{env.JF2_HOST}}
          BE_HOST=${{env.BE_HOST}}
          BE_JF_SECURE_CONNECTION=true
          BE_JF_ADDRESSES=${{env.JF1_HOST}} ${{env.JF2_HOST}}
          PROMETHEUS_TARGETS=jellyfish1:9568,${{secrets.STAGING2_IP}}:9568
          GF_SECURITY_ADMIN_PASSWORD=${{secrets.GF_SECURITY_ADMIN_PASSWORD}}
          GF_SECURITY_ADMIN_USER=${{secrets.GF_SECURITY_ADMIN_USER}}" > .env

      - name: Remove old containers on first host
        uses: JimCronqvist/action-ssh@master
        with:
          hosts: ${{ secrets.STAGING_IP }}
          privateKey: ${{ secrets.SSH_PRIV_KEY }}
          command: |
            docker ps -aq | xargs -r docker stop | xargs -r docker rm 

      - name: Deploy docker compose to a pre-configured server on first host
        uses: TapTap21/docker-remote-deployment-action@v1.1
        with:
          remote_docker_host: ${{ secrets.STAGING_IP }}
          ssh_private_key: ${{ secrets.SSH_PRIV_KEY }}
          ssh_public_key: ${{ secrets.SSH_PUB_KEY }}
          stack_file_name: ${{ env.COMPOSE_FILE_NAME }}
          args: -p ${{ env.PROJECT }} --env-file .env up -d --remove-orphans --build jellyfish1 frontend backend prometheus grafana

  deploy2:
    runs-on: ubuntu-latest
    steps:  
      - uses: actions/checkout@v2
        
      - name: Prepare .env file for the deployment
        id: variables_population
        run: |
          echo "JF_SERVER_API_TOKEN=${{secrets.SERVER_API_TOKEN}}
          JF_CHECK_ORIGIN=false
          JF_PORT=5002
          JF1_IP=${{secrets.STAGING_IP}}
          JF2_IP=${{secrets.STAGING2_IP}}
          JF2_HOST=${{env.JF2_HOST}}" > .env
      - name: Remove old containers on second host
        uses: JimCronqvist/action-ssh@master
        with:
          hosts: ${{ secrets.STAGING2_IP }}
          privateKey: ${{ secrets.SSH_PRIV_KEY }}
          command: |
            docker ps -aq | xargs -r docker stop | xargs -r docker rm 

      - name: Deploy docker compose to a pre-configured server on second host
        uses: TapTap21/docker-remote-deployment-action@v1.1
        with:
          remote_docker_host: ${{ secrets.STAGING2_IP }}
          ssh_private_key: ${{ secrets.SSH_PRIV_KEY }}
          ssh_public_key: ${{ secrets.SSH_PUB_KEY }}
          stack_file_name: ${{ env.COMPOSE_FILE_NAME }}
          args: -p ${{ env.PROJECT }} --env-file .env up -d --remove-orphans --build jellyfish2
